apiVersion: v1
kind: Pod
metadata:
  labels:
    app: php-app
  name: nginx-phpfpm
  namespace: default
spec:
  containers:
  - image: php:7.2-fpm-alpine
    name: php-fpm-container
    volumeMounts:
    - mountPath: /var/www/html
      name: shared-files
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
    - mountPath: /var/www/html
      name: shared-files
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-config-volume
      subPath: nginx.conf

  volumes:
  - emptyDir: {}
    name: shared-files
  - configMap:
      defaultMode: 420
      name: nginx-config
    name: nginx-config-volume

  ## in config-map nginx root path is /var/www/html, so both containers are mounted at the same path.